In [2]:
import numpy as np

# numpy 数字化Python，研究数据
# 快捷键执行代码：Shift + Enter

In [ ]:
# 之前列表[1,2,3,4,5]
# 序号：0、1、2……
l = [1,2,3,4,5]
print('打印输出列表：',l)

print('保存批量数据：',l[0])

print('取出最后一个数据：', l[4])
print('取出最后一个数据：', l[-1])

In [ ]:
print('取出两个：', l[1:3]) # 从哪里取到哪里，左开右闭，右边取不到

In [9]:
print('取出两个:', l[[1,2]]) # 一次取两个！！！

TypeError: list indices must be integers or slices, not list

In [17]:
l >= 3

TypeError: '>=' not supported between instances of 'list' and 'int'

In [12]:
# 创建NumPy数组np.array(列表)
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [13]:
arr[[1,2]] # NumPy数组可以自由的取多个数据~

array([2, 3])

In [15]:
cond = arr >= 3 # 大于等于3的数字筛选！
cond
arr[cond]

array([3, 4, 5])

# 不同创建方式

In [18]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [20]:
np.full(shape = 20,fill_value = 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14,
       3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [21]:
np.random.randint(0,100,size = 10)

array([52, 29, 96, 49, 64, 78, 57,  2, 12, 25])

In [22]:
np.random.randn(10) # 正态分布，平均值是0，标准差是1

array([ 0.15074252, -0.64514677, -1.21408289,  0.50651639,  0.23750016,
       -0.76550083,  1.35558973, -0.86062184,  0.00539801,  0.11297829])

In [26]:
np.linspace(1,99,50) # 等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [30]:
np.set_printoptions(suppress = True) # 不显示科学技术法
np.logspace(0,10,base=3,num = 11) # 等比数列
# shift + tab:查看 方法的参数，工具查看

array([    1.,     3.,     9.,    27.,    81.,   243.,   729.,  2187.,
        6561., 19683., 59049.])

In [31]:
# 二维数组
np.random.randint(0,10,size = (3,5))

array([[8, 8, 2, 2, 5],
       [0, 5, 4, 5, 6],
       [3, 2, 9, 0, 8]])

In [32]:
# 三维数组
np.random.randint(0,10,size = (2,3,4))

array([[[7, 2, 6, 7],
        [4, 2, 4, 6],
        [0, 0, 4, 7]],

       [[9, 4, 2, 4],
        [9, 1, 0, 6],
        [2, 9, 6, 6]]])

# 数据查看

In [33]:
arr = np.random.random(size = (3,5))
arr

array([[0.31700569, 0.7834003 , 0.73379397, 0.50188299, 0.37087323],
       [0.10256064, 0.23178487, 0.75848242, 0.64463791, 0.58171891],
       [0.83035759, 0.54774004, 0.44205139, 0.61796148, 0.78994968]])

In [34]:
arr.shape # 形状

(3, 5)

In [35]:
arr.dtype # 数据类型float 64 （64位）

dtype('float64')

In [36]:
arr.size # 数量

15

In [37]:
arr.ndim # 查看维度

2

In [38]:
# 0、1----> 位
# 8个位 ---> 字节
# 64 / 8 = 8
arr.itemsize # 每个元素大小，对应8个字节

8

# 数组保存

In [44]:
for i in range(0,10,3): # Python 自带，颜色绿色的~
    print(i)

0
3
6
9


In [46]:
[i for i in range(0,10,3)] # 列表生成式

[0, 3, 6, 9]

In [47]:
arr = np.arange(0,10,3) # NumPy的方法，功能类似

# 当前目录
np.save('./data1',arr) # 保存数据

In [48]:
np.load('./data1.npy') # 取出数据

array([0, 3, 6, 9])

In [49]:
arr2 = np.logspace(0,10,base = 2,num = 11)
arr2

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [53]:
np.savez('./data2.npz',arr1 = arr, arr2 = arr2) # 保存多个

In [54]:
np.load('./data2.npz')['arr1']

array([0, 3, 6, 9])

In [56]:
np.load('./data2.npz')['arr2']

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

In [57]:
np.save('./数据',arr2)

In [58]:
np.load('./数据.npy')

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

# 数据类型

In [ ]:
# 整数
# 浮点数
# 字符串：我爱北京天安门

In [60]:
arr = np.array([2,4,5],dtype = np.int16)
arr

array([2, 4, 5], dtype=int16)

In [61]:
arr = np.array([2,4,5],dtype = np.int32)
arr

array([2, 4, 5], dtype=int32)

In [64]:
arr = np.random.randint(0,100,size = (100,50),dtype = np.int8)
np.save('./data3_int8',arr)

In [65]:
arr = np.random.randint(0,100,size = (100,50),dtype = np.int64)
np.save('./data4_int64',arr)

In [66]:
# uint8 无符号，没有负号，没有负数

# int8 
2**8 # -128 ~ 127 包含0

256

In [70]:
arr1 = np.arange(-128,128,dtype = np.int8)
arr1

array([-128, -127, -126, -125, -124, -123, -122, -121, -120, -119, -118,
       -117, -116, -115, -114, -113, -112, -111, -110, -109, -108, -107,
       -106, -105, -104, -103, -102, -101, -100,  -99,  -98,  -97,  -96,
        -95,  -94,  -93,  -92,  -91,  -90,  -89,  -88,  -87,  -86,  -85,
        -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,  -76,  -75,  -74,
        -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,  -64,  -63,
        -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,  -52,
        -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
        -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,
        -29,  -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,
        -18,  -17,  -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,
         -7,   -6,   -5,   -4,   -3,   -2,   -1,    0,    1,    2,    3,
          4,    5,    6,    7,    8,    9,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   19,   20,   21,   

In [71]:
# 0 ~ 255 刚好是256个数字，只能表示整数 0 ~ 255
arr2 = np.arange(-128,128,dtype = np.uint8)
arr2

array([128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
       154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
       167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
       180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
       232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
       245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  5

In [72]:
arr1.dtype

dtype('int8')

In [75]:
# 转换其数据类型，为我们生成新的数组
arr3 = arr1.astype(np.float32)
arr3

array([-128., -127., -126., -125., -124., -123., -122., -121., -120.,
       -119., -118., -117., -116., -115., -114., -113., -112., -111.,
       -110., -109., -108., -107., -106., -105., -104., -103., -102.,
       -101., -100.,  -99.,  -98.,  -97.,  -96.,  -95.,  -94.,  -93.,
        -92.,  -91.,  -90.,  -89.,  -88.,  -87.,  -86.,  -85.,  -84.,
        -83.,  -82.,  -81.,  -80.,  -79.,  -78.,  -77.,  -76.,  -75.,
        -74.,  -73.,  -72.,  -71.,  -70.,  -69.,  -68.,  -67.,  -66.,
        -65.,  -64.,  -63.,  -62.,  -61.,  -60.,  -59.,  -58.,  -57.,
        -56.,  -55.,  -54.,  -53.,  -52.,  -51.,  -50.,  -49.,  -48.,
        -47.,  -46.,  -45.,  -44.,  -43.,  -42.,  -41.,  -40.,  -39.,
        -38.,  -37.,  -36.,  -35.,  -34.,  -33.,  -32.,  -31.,  -30.,
        -29.,  -28.,  -27.,  -26.,  -25.,  -24.,  -23.,  -22.,  -21.,
        -20.,  -19.,  -18.,  -17.,  -16.,  -15.,  -14.,  -13.,  -12.,
        -11.,  -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,
         -2.,   -1.,

In [74]:
arr1.dtype

dtype('int8')

# 数组运算

In [76]:
nd = np.random.randint(0,10,size = (3,5))
nd

array([[6, 4, 9, 6, 1],
       [6, 1, 9, 6, 2],
       [1, 0, 3, 7, 7]])

In [81]:
nd ** 3

array([[216,  64, 729, 216,   1],
       [216,   1, 729, 216,   8],
       [  1,   0,  27, 343, 343]])

In [82]:
np.power(nd,3)

array([[216,  64, 729, 216,   1],
       [216,   1, 729, 216,   8],
       [  1,   0,  27, 343, 343]])

In [83]:
nd /2

array([[3. , 2. , 4.5, 3. , 0.5],
       [3. , 0.5, 4.5, 3. , 1. ],
       [0.5, 0. , 1.5, 3.5, 3.5]])

In [84]:
nd % 2

array([[0, 0, 1, 0, 1],
       [0, 1, 1, 0, 0],
       [1, 0, 1, 1, 1]])

In [85]:
nd // 2

array([[3, 2, 4, 3, 0],
       [3, 0, 4, 3, 1],
       [0, 0, 1, 3, 3]])

In [86]:
nd > 5

array([[ True, False,  True,  True, False],
       [ True, False,  True,  True, False],
       [False, False, False,  True,  True]])

In [88]:
nd == 6

array([[ True, False, False,  True, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False]])

In [89]:
nd

array([[6, 4, 9, 6, 1],
       [6, 1, 9, 6, 2],
       [1, 0, 3, 7, 7]])

In [90]:
nd += 100 # 在原来的基础上加上100 ~ nd = nd + 100

In [91]:
nd

array([[106, 104, 109, 106, 101],
       [106, 101, 109, 106, 102],
       [101, 100, 103, 107, 107]])

In [92]:
nd /= 3

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [94]:
nd //= 3

In [95]:
nd

array([[35, 34, 36, 35, 33],
       [35, 33, 36, 35, 34],
       [33, 33, 34, 35, 35]])

In [96]:
nd2 = nd.copy()
nd2

array([[35, 34, 36, 35, 33],
       [35, 33, 36, 35, 34],
       [33, 33, 34, 35, 35]])

In [97]:
nd -= 10
nd

array([[25, 24, 26, 25, 23],
       [25, 23, 26, 25, 24],
       [23, 23, 24, 25, 25]])

# 索引和切片

## 一维数组索引和切片

In [98]:
arr = np.random.randint(0,100,size = 10)
arr

array([94, 29, 19, 73, 26, 65, 19, 69, 70, 92])

In [101]:
arr[[0,3,5]] # 索引，根据位置取相应数据

array([94, 73, 65])

In [102]:
arr[3:6] # 切片，切蛋糕

array([73, 26, 65])

In [103]:
arr[3:6:2] # 从3到6，2表示两个中取一个

array([73, 65])

In [104]:
arr[:] # 默认全部数据

array([94, 29, 19, 73, 26, 65, 19, 69, 70, 92])

In [106]:
arr[::3]

array([94, 73, 19, 92])

In [109]:
arr[::-3] # 倒过来了，取数据

array([92, 19, 73, 94])

## 二维数组索引和切片

In [110]:
arr2 = np.random.randint(0,100,size = (3,5))
arr2

array([[50, 35, 59, 75, 63],
       [65, 90, 70, 40, 46],
       [89,  3, 57, 19, 46]])

In [111]:
# 逗号隔开
arr2[0,2]

59

In [112]:
arr2[1,[1,2]] # 第二行，第二列和第三列数据

array([90, 70])

In [114]:
# 第二行和第三行以及第四列和第五列的数据
# 索引和切片配合使用
arr2[[1,2],3:]

array([[40, 46],
       [19, 46]])

In [117]:
arr2[[1,2]][:,[3,4]]

array([[40, 46],
       [19, 46]])

In [119]:
arr2[[0,2]][:,[0,2,4]]

array([[50, 59, 63],
       [89, 57, 46]])

In [123]:
arr2[2,[2,4]] = 1024
arr2

array([[  50,   35,   59,   75,   63],
       [  65,   90,   70,   40,   46],
       [  89,    3, 1024,   19, 1024]])

## 花式索引

In [124]:
arr = np.random.randint(0,100,size = 20)
arr


array([49, 95, 26, 91,  6, 60, 50, 45, 25, 40, 52, 96,  0, 13, 54, 85, 70,
       47, 69, 22])

In [125]:
arr[[3,5,7]] # 花式索引

array([91, 60, 45])

In [126]:
cond = arr > 60
arr[cond] # boolean花式索引

array([95, 91, 96, 85, 70, 69])

l = [1,2,3,4,5]
print('打印输出列表：',l)

print('保存批量数据：',l[0])

print('取出最后一个数据：', l[4])
print('取出最后一个数据：', l[-1])

### tee

In [ ]:
print(2)